---
- name: Persist GANDI_LIVEDNS_KEY
  lineinfile:
    dest: "{{ item.path }}"
    regexp: "^GANDI_LIVEDNS_KEY"
    line: "{{ item.should_export | ternary('export ', '') }}GANDI_LIVEDNS_KEY={{ acme_gandi_livedns_key }}"
    state: present
    create: yes
  with_items:
    - { path: "/etc/environment", should_export: false }
    - { path: "/etc/profile.d/acme_gandi_dns.sh", should_export: true }
