---
- name: Persist OVH_AK
  lineinfile:
    dest: "{{ item.path }}"
    regexp: "^OVH_AK"
    line: "{{ item.should_export | ternary('export ', '') }}OVH_AK={{ acme_ovh_application_key }}"
    state: present
    create: yes
  with_items:
    - { path: "/etc/environment", should_export: false }
    - { path: "/etc/profile.d/acme_ovh_dns.sh", should_export: true }

- name: Persist OVH_AS
  lineinfile:
    dest: "{{ item.path }}"
    regexp: "^OVH_AS"
    line: "{{ item.should_export | ternary('export ', '') }}OVH_AS={{ acme_ovh_application_secret }}"
    state: present
    create: yes
  with_items:
    - { path: "/etc/environment", should_export: false }
    - { path: "/etc/profile.d/acme_ovh_dns.sh", should_export: true }

- name: Persist OVH_CK
  lineinfile:
    dest: "{{ item.path }}"
    regexp: "^OVH_CK"
    line: "{{ item.should_export | ternary('export ', '') }}OVH_CK={{ acme_ovh_consumer_key }}"
    state: present
    create: yes
  with_items:
    - { path: "/etc/environment", should_export: false }
    - { path: "/etc/profile.d/acme_ovh_dns.sh", should_export: true }
