---
- name: INCLUDE | Install acme.sh
  import_tasks: install.yml

- name: INCLUDE | Configure OVH credentials for DNS api
  import_tasks: configure_ovh.yml
  when: acme_configure_ovh_dns_api | bool

- name: INCLUDE | Configure Gandi credentials for DNS api
  import_tasks: configure_gandi.yml
  when: acme_configure_gandi_dns_api | bool

- name: INCLUDE | Configure certificates
  include_tasks: issue_certs.yml
  when: certs_to_issue
  with_items: "{{ certs_to_issue }}"
  loop_control:
    loop_var: cert
