---
- name: Verify
  hosts: all
  tasks:
    - name: Check if acme.sh is present
      stat:
        path: "/home/acme/acme/acme.sh"
      register: acme_script

    - name: Verify installation
      assert:
        that:
        - "acme_script.stat.exists"

    - name: Check if gandi cer is present
      stat:
        path: "/root/.acme.sh/{{ lookup('env','UNICODA_ACME_CERT_1') }}/{{ lookup('env','UNICODA_ACME_CERT_1') }}.cer"
      register: gandi_cer

    - name: Verify gandi certificate issue
      assert:
        that:
          - "gandi_cer.stat.exists"

    - name: Test gandi renew command
      command: >
        ./acme.sh \
        --test \
        --renew \
        -d {{ lookup('env','UNICODA_ACME_CERT_1') }} \
        -d {{ lookup('env','UNICODA_ACME_CERT_2') }} \
        --force \
        --log
      args:
        chdir: "/home/acme/acme"

    - name: Check if ovh cer is present
      stat:
        path: "/root/.acme.sh/{{ lookup('env','UNICODA_ACME_CERT_OVH') }}/{{ lookup('env','UNICODA_ACME_CERT_OVH') }}.cer"
      register: ovh_cer

    - name: Verify ovh certificate issue
      assert:
        that:
          - "ovh_cer.stat.exists"

    - name: Test ovh renew command
      command: >
        ./acme.sh \
        --test \
        --renew \
        -d {{ lookup('env','UNICODA_ACME_CERT_OVH') }} \
        --force \
        --log
      args:
        chdir: "/home/acme/acme"
