---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install yamllint

      - name: Lint code.
        run: |
          yamllint .

  test:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - debian10

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install ansible molecule[docker] yamllint ansible-lint

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
          UNICODA_ACME_MAIL: ${{ secrets.acme_email }}
          UNICODA_OVH_AK: ${{ secrets.ovh_ak }}
          UNICODA_OVH_AS: ${{ secrets.ovh_as }}
          UNICODA_OVH_CK: ${{ secrets.ovh_ck }}
          UNICODA_GANDI_LIVEDNS_KEY: ${{ secrets.gandi_livedns_key }}
          UNICODA_ACME_CERT_1: ${{ secrets.acme_cert_1 }}
          UNICODA_ACME_CERT_2: ${{ secrets.acme_cert_2 }}
          UNICODA_ACME_CERT_OVH: ${{ secrets.acme_cert_ovh }}
        # working-directory: molecule
